services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: finops
      POSTGRES_PASSWORD: finops
      POSTGRES_DB: finops
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro

  api:
    build:
      context: .                # <- project root as build context
      dockerfile: api/Dockerfile
    env_file: .env
    depends_on: [postgres]
    ports: ["8080:8080"]
    volumes:
      - ./policies:/app/policies:ro

  worker:
    build:
      context: .                # <- project root as build context
      dockerfile: worker/Dockerfile
    env_file: .env
    depends_on: [postgres]
    volumes:
      - ./policies:/app/policies:ro

volumes:
  pgdata:

